### ISSUE TITLE
getPackageManager().getActivityInfo(getIntent().getComponent()... 方式获取activityInfo造成的问题

### ISSUE THREAD

**Issue by FreemanQ** [FinalLody/Direct-Load-apk#11]
插件中使用了NativeActivity，NativeActivity在oncreate的时候使用了getPackageManager().getActivityInfo(getIntent().getComponent(), PackageManager.GET_META_DATA)去获取activityInfo，然后由这个activityinfo再去取applicationInfo中的nativeLibraryDir，这时取到的是未被baseContext覆盖过的so目录地址

06-05 18:00:52.979: W/System.err(10627): java.lang.IllegalArgumentException: Unable to find native library: main
06-05 18:00:52.989: W/System.err(10627): 	at android.app.NativeActivity.onCreate(NativeActivity.java:171)
06-05 18:00:52.989: W/System.err(10627): 	at com.unity3d.player.UnityPlayerNativeActivity.onCreate(Unknown Source)
06-05 18:00:52.989: W/System.err(10627): 	at android.app.Activity.performCreate(Activity.java:5243)
06-05 18:00:52.989: W/System.err(10627): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
06-05 18:00:52.989: W/System.err(10627): 	at com.lody.plugin.control.PluginActivityControl.callOnCreate(PluginActivityControl.java:173)
06-05 18:00:52.989: W/System.err(10627): 	at com.lody.plugin.LActivityProxy.onCreate(LActivityProxy.java:269)
06-05 18:00:52.989: W/System.err(10627): 	at android.app.Activity.performCreate(Activity.java:5243)
06-05 18:00:52.989: W/System.err(10627): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
06-05 18:00:52.989: W/System.err(10627): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2140)
06-05 18:00:52.999: W/System.err(10627): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2226)
06-05 18:00:52.999: W/System.err(10627): 	at android.app.ActivityThread.access$700(ActivityThread.java:135)
06-05 18:00:52.999: W/System.err(10627): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1397)
06-05 18:00:52.999: W/System.err(10627): 	at android.os.Handler.dispatchMessage(Handler.java:102)
06-05 18:00:52.999: W/System.err(10627): 	at android.os.Looper.loop(Looper.java:137)
06-05 18:00:52.999: W/System.err(10627): 	at android.app.ActivityThread.main(ActivityThread.java:4998)
06-05 18:00:52.999: W/System.err(10627): 	at java.lang.reflect.Method.invokeNative(Native Method)
06-05 18:00:52.999: W/System.err(10627): 	at java.lang.reflect.Method.invoke(Method.java:515)
06-05 18:00:52.999: W/System.err(10627): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:777)
06-05 18:00:53.009: W/System.err(10627): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:593)
06-05 18:00:53.009: W/System.err(10627): 	at dalvik.system.NativeStart.main(Native Method)
06-05 18:00:52.979: W/System.err(10627): java.lang.IllegalArgumentException: Unable to find native library: main
06-05 18:00:52.989: W/System.err(10627): 	at android.app.NativeActivity.onCreate(NativeActivity.java:171)
06-05 18:00:52.989: W/System.err(10627): 	at com.unity3d.player.UnityPlayerNativeActivity.onCreate(Unknown Source)
06-05 18:00:52.989: W/System.err(10627): 	at android.app.Activity.performCreate(Activity.java:5243)
06-05 18:00:52.989: W/System.err(10627): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
06-05 18:00:52.989: W/System.err(10627): 	at com.lody.plugin.control.PluginActivityControl.callOnCreate(PluginActivityControl.java:173)
06-05 18:00:52.989: W/System.err(10627): 	at com.lody.plugin.LActivityProxy.onCreate(LActivityProxy.java:269)
06-05 18:00:52.989: W/System.err(10627): 	at android.app.Activity.performCreate(Activity.java:5243)
06-05 18:00:52.989: W/System.err(10627): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
06-05 18:00:52.989: W/System.err(10627): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2140)
06-05 18:00:52.999: W/System.err(10627): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2226)
06-05 18:00:52.999: W/System.err(10627): 	at android.app.ActivityThread.access$700(ActivityThread.java:135)
06-05 18:00:52.999: W/System.err(10627): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1397)
06-05 18:00:52.999: W/System.err(10627): 	at android.os.Handler.dispatchMessage(Handler.java:102)
06-05 18:00:52.999: W/System.err(10627): 	at android.os.Looper.loop(Looper.java:137)
06-05 18:00:52.999: W/System.err(10627): 	at android.app.ActivityThread.main(ActivityThread.java:4998)
06-05 18:00:52.999: W/System.err(10627): 	at java.lang.reflect.Method.invokeNative(Native Method)
06-05 18:00:52.999: W/System.err(10627): 	at java.lang.reflect.Method.invoke(Method.java:515)
06-05 18:00:52.999: W/System.err(10627): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:777)
06-05 18:00:53.009: W/System.err(10627): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:593)
06-05 18:00:53.009: W/System.err(10627): 	at dalvik.system.NativeStart.main(Native Method)

**Comment by FreemanQ** [comment]
1、在启动activity前需要重新设置下pluginActivity中的ComponentName对象；
2、在自定义的BaseContext中需要重写getPackageManager方法，返回一个自定义的PackageManager；3、在自定义的PackageManager中，重写getActivityInfo方法，在里面取到之前重新设置的ComponentName再做判断和替换。
